export default {
  signIn: 'POST /user/signin',
  signUp: 'POST /user/signup',
  editUserProfile: 'POST /user/editProfile',
  searchUsers: '/user/search',
  me: '/user/me',
  newToken: '/user/newToken',
  getAllUsers: '/user',
  editUserRole: 'POST /user/changeRole',
  getRandomText: '/text/random',
  getTextById: '/text',
  deleteTextById: 'POST /text/delete',
  addNewText: 'POST /text',
  editNewText: 'POST /text/update',
  createTextHistory: 'POST /historyText',
  getHistoryTextById: '/historyText',
  getTournamentList: '/turnir',
  getTournamentById: '/turnir',
  createTournamentUser: 'POST /turnirUser',
  getTournamentusers: '/turnirUser/byTurnir',
  addTurnir: 'POST /turnir',
  updateTurnir: 'POST /turnir/update',
  deleteTurnir: 'POST /turnir/delete',
  beginWrite: 'POST /historyText/begin',
  writeWord: 'POST /historyText/writeWord',
  endWrite: 'POST /historyText/end',
  beginWriteTurnir: 'POST /turnirUser/begin',
  writeWordTurnir: 'POST /turnirUser/writeWord',
  endWriteTurnir: 'POST /turnirUser/end',
  rejectWpm: 'POST /turnirUser/rejectWpm',
  blockUser: 'POST /user/blockUser',
  unBlockUser: 'POST /user/unBlockUser',
}
